# Generated by Django 2.1.2 on 2018-10-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('thumb', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'home',
            },
        ),
        migrations.DeleteModel(
            name='home',
        ),
    ]
