# Generated by Django 2.1.2 on 2018-10-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181026_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('thumb', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'projects',
            },
        ),
    ]
