# Generated by Django 2.1.2 on 2018-10-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projectsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsdb',
            name='thumb1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projectsdb',
            name='thumb2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projectsdb',
            name='thumb3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
