# Generated by Django 2.1.2 on 2018-10-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_constructionpicsdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='elevationPicsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('thumb', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'elevationPics',
            },
        ),
    ]
