# Generated by Django 2.1.2 on 2018-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_teamdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('pic', models.ImageField(blank=True, upload_to='')),
                ('story', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'blog',
            },
        ),
    ]
