# Generated by Django 2.1.2 on 2018-10-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blogdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonialDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('testimonial', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'testimonials',
            },
        ),
    ]
