# Generated by Django 2.1.2 on 2018-10-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contactusdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusdb',
            options={'verbose_name_plural': 'contactUs'},
        ),
    ]
