# Generated by Django 2.1.2 on 2018-10-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181028_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusdb',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactusdb',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactusdb',
            name='email',
            field=models.EmailField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='contactusdb',
            name='message',
            field=models.TextField(default='dafault'),
            preserve_default=False,
        ),
    ]
