# Generated by Django 2.1.2 on 2018-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181028_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusdb',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=200),
        ),
    ]
