# Generated by Django 2.1.2 on 2018-10-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20181028_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusdb',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
