# Generated by Django 2.1.2 on 2018-10-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181028_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusdb',
            old_name='email',
            new_name='sender',
        ),
    ]
