# Generated by Django 2.1.2 on 2018-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20181028_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusdb',
            old_name='message',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='contactusdb',
            name='sender',
        ),
        migrations.AddField(
            model_name='contactusdb',
            name='phone',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
